### ISSUE TITLE
Linter causes NPM to throw an error when being run from inside NPM scripts

### ISSUE THREAD

**Issue by stewartknapman** [Shopify/theme-check#110]
Hey team,

First off thank you so much for building this tool. I think this is going to be super beneficial to a lot of theme developers.

While I was doing a quick evaluation to see if it would run inside our teams existing build tools (using NPM scripts) I noticed it was causing NPM to throw an error. I don't know if the error goes away if the linter passes—we likely don't have any projects that would 100% pass right out of the gate.

Steps to replicate:
1. installed via Homebrew
2. added an npm script to package.json i.e. `... "scripts": { "themeLint": "theme-check" }, ...`
3. run `npm run themeLint` command

<img width="2460" alt="Screen Shot 2021-01-20 at 11 51 46 AM" src="https://user-images.githubusercontent.com/1373290/105105088-4337b880-5b18-11eb-9728-bc894e4ad2ae.png">

**Comment by macournoyer** [comment]
Thanks for the kind words, glad you like it!

Yes, this is because theme-check is reporting errors, in which case it will return with an exit code of 1, which cause `npm run` to throw this error.

If you had no offenses reported by theme-check, it will return w/ an exit code of 0, and this won't happen.

If you want to ignore some checks, see https://github.com/Shopify/theme-check#configuration. Or ignore all translation checks use the `-x translation` option.
