### ISSUE TITLE
Allow specifying of directory or files to check on command

### ISSUE THREAD

**Issue by yishus** [Shopify/theme-check#135]
eg.
```
$ theme-check app spec snippets/something.liquid
```

This would facilitate current file only check for IDE plugins/extensions. We can explore linting on keypress by limiting the scope of scanned files.

**Comment by macournoyer** [comment]
I think for this we will need a way to tell which checks apply to a particular file, and which require scanning the full theme.

For example: `UndefinedObject`, `NestedSnippet`, `UnusedSnippet`, and `UnusedAssign` must scan all Liquid files to work. And `MissingRequiredTemplateFiles` apply to the full theme (all those have have a `dev on_end`).

Maybe we always run those ^, and then run the other checks only on the specific file?

But, in the context of LSP, we might not even need all this, because I think LSP keeps the diagnostics until you send an empty one right? So maybe only limiting this to LSP for now?
