### ISSUE TITLE
Frequently get MissingTemplate for snippets that exist.

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#201]
I'm noticing quite frequently that I'm getting an error message stating some snippets can't be found, yet they definitely exist.
![image](https://user-images.githubusercontent.com/18140157/110942097-37ef5500-8331-11eb-8b4d-87b096ccea33.png)

**Comment by charlespwd** [comment]
Where is the `.theme-check.yml` located? What is the value of the `root:` option?

Wondering if this is because we're looking for `$root/snippets/svg-sprite.liquid` with the wrong root of if it's a bug. (Since I'm seeing src/theme/snippets in that screenshot, which means that either `.theme-check.yml` should be in the theme folder _or_ the root configuration should say `src/theme`)

**Comment by ConduciveMammal** [comment]
Ahhh wait, yeah sorry about that. It's one of the projects without the theme-check config. Wonder if it might be possible to create a default global config so this doesn't trip people up?
