### ISSUE TITLE
Please help me fix this bash script to just run theme-check on the staged paths.

### ISSUE THREAD

**Issue by agentlewis** [Shopify/theme-check#355]
Hey all,

I decided I wanted to setup theme-check with husky on a git hook. I have all the other bits working but am not sure how to correctly pipe the paths (or if its possible) from `git diff` to `theme-check`.

What I currently have:

```Bash
git diff --name-only --cached | theme-check
```

Any help would be appreciated with virtual hugs through the meta-fabric of time and space :)

**Comment by charlespwd** [comment]
Right now, that won't work because theme-check has some checks that are theme aware (e.g. translations not used, unused snippets, etc.). As such, when you run theme-check, you need a theme root and not individual files.

If you don't want to be blocked by missing feature, you might want to do this the other way around by intersecting the results instead.

e.g.

```
project_root="."
merge_base="$(git ...)"
files="$(git diff --name-only --cached $merge_base)"
theme_check_results="$(theme-check)"
filter="$(echo $files | ...)
echo "$theme_check_results" | grep -A1 "$filter"
```

But I'm not even sure that would work super well. We might want to visit #220 to output as JSON. That would make the intersection slightly easier to do.

**Comment by charlespwd** [comment]
Hi @agentlewis, this issue is stale and hasn't moved in a while. Feel free to reopen if you want to further the discussion.
