### ISSUE TITLE
Exception while running `SpaceInsideBraces#on_tag`:

### ISSUE THREAD

**Issue by catboxer** [Shopify/theme-check#453]
`Template: `sections/featured-product.liquid`
Node: `Liquid::If`
Markup:
```
if section.settings.enable_payment_button and product.has_only_default_variant
```
Check options: `{}
`
Theme Check Version: 1.4.0
Ruby Version: 3.0.2
Platform: x86_64-darwin19
Muffin mode: activated`

**Comment by charlespwd** [comment]
Hi @catboxer, I believe this has been fixed in the latest vestion (we're at 1.6.0). 

You did not include the stacktrace, so I do not know if this has been started via the Shopify CLI or theme-check itself.

To upgrade:

* If you have installed it via the Shopify CLI on brew, easiest way is to reinstall it to get the latest version of theme-check.

  ```
  brew uninstall shopify-cli
  brew install shopify-cli
  ```

* If you have installed it via Shopify CLI via the gem, reinstall it.

  ```
  gem uninstall shopify-cli
  gem install shopify-cli
  ```

* If you have installed theme-check via brew, upgrade it

  ```
  brew update && brew upgrade theme-check
  ```

* If you have installed it via the gem, upgrade it.

  ```
  gem update theme-check
  ```
