### ISSUE TITLE
Does theme-check really need to run a test of every file each time I save a file?

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/theme-check#507]
![image](https://user-images.githubusercontent.com/18140157/142603466-48290f18-a069-4b57-85c7-cdd5b3e3204c.png)

When saving a file, I notice theme-check runs a partial check of the entire theme. This seems like a terrible waste of resources and time.

**Comment by charlespwd** [comment]
It's actually not. It's running the single file check on the file you just saved, and the "whole theme" checks on the rest (e.g. matching translations, missing translations, etc.) 

Might be worth investigating if we could get around that but I'm not sure we could.

**Comment by ConduciveMammal** [comment]
Hmmm it definitely seems to be checking everything, or at least running through everything.

Unless I'm misunderstanding what's happening here when I save?

https://user-images.githubusercontent.com/18140157/142637841-35406503-7f13-4aa8-a3c3-587f1e6b4851.mov

**Comment by charlespwd** [comment]
Yeah the progress bar might be confusing. We discussed this during code review 😅 

It's really analyze_files([current_file]) + analyze_theme(:only_whole_theme_checks)

But it needs to go through the other files to do the "whole theme" checks. 

So it's scanning your file and does all the heavy work (syntax, spaces, remote asset, etc. etc.) but not on the other ones. It will go _through_ the other ones (to check if translations are missing or are now fixed because of a change to the current file) but it will only check the checks that are considered "whole theme" checks. 

And by "whole theme" checks, I mean: checks that are done across multiple files. For now those are mostly: missing files, missing translations, matching translations checks, unused snippets checks. 

You should notice that the first theme-check that you run (e.g. when firing up the editor, or by restarting the theme-check server) is much slower. That's because the first check runs _all the checks_ on _all the files_.

**Comment by vfonic** [comment]
> So it's scanning your file and does all the heavy work (syntax, spaces, remote asset, etc. etc.) but not on the other ones. It will go through the other ones (to check if translations are missing or are now fixed because of a change to the current file) but it will only check the checks that are considered "whole theme" checks.

I just checked how big are translation files. In four themes/stores that I'm working on: 12KB, 17KB, 21KB, 22KB

Maybe these translations can be "cached" in memory so you don't have to check all files, but just the diff with the current file?

I'm not sure what other checks are whole theme checks.
