### ISSUE TITLE
How theme-check validates schema?

### ISSUE THREAD

**Issue by tomaszs** [Shopify/theme-check#544]
I have noticed that the extension for VSCode shows errors on schema sometimes. It does not indicate where the error occurs, what makes it hard to debug.

I wanted to check with other JSON validator online, but all validators I check tell the schema is valid JSON.

Are there any specific settings of the validator above JSON standard?

**Comment by charlespwd** [comment]
I believe that you would have a longer explanation if you run theme-check from the command line instead of from the editor. Might be wrong.

It really is nothing more than JSON.parse(...). So probably a trailing comma or one of the tags with a duplicate brace e.g. `{% schema %}}` or `{{% endschema %}`.

**Comment by charlespwd** [comment]
Oh. In this case, it's a _formatting_ issue. You should be able to click on the quickfix icon to fix it.

https://user-images.githubusercontent.com/4990691/152213802-0fab41ce-64c4-4b27-9c9e-9b9b42a91ce5.mp4
